env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - eslint:recommended
  - react-app
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  react/jsx-filename-extension: [0, { "extensions": [".js", ".jsx"] }],
}